apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/kube-state-metrics
  ref:
    tag: 5.0.9
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
    namespace: default
  values:
    installCRDs: true
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi

---
