apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: default
spec:
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: cert-manager
      version: "v1.18.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: default
  values:
    installCRDs: true
    resources:
      requests:
        memory: 50m
---
