apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-autoscaler-civo
  namespace: kube-system
spec:
  encryptedData:
    CIVO_API_KEY: AgCH6JbTof21uDEX7Ec2hanPfJIdEnKVqBU05dHKsl2Q8jyRGYbvRnn+GFADwFIHNq3L8HgFpo8SQzhwYKKuLgTckquXSpirnuOfs0vPswapUN2kzY9D/1TWF8FjwkdpB0sXXNwsxHvEg4zd/nHeioRWlvMWQWz0J39GDfU5noIo351zEm+dmBIjsjt3m6bi8J5svANzabg46cUCMBe2ZlF8VQE9Eby4rpP5ZjILS8K9IwIfUuuJeoU1V9uIHuj0L4011I0Cbtrt1WNyv4GthNa/0JXnjBG93FnGnNFb0HGlTz1nbz8122z4EVX2kSVAmcg4kgA/qprBNhjX5p8kb4/jVYBzTitusdxUvZi1oYV6P21ONkvd85YF+OVOW0+NrOhM2sMENLk0GN9AOMkAW01SKzBmlqgZEzBsY5XS49v7Vty5wnhqSU95jiXWFsdSseeqMynpu0xEHdtXNgnz6baRZ2Gz60fpg78rGW78/QRtL5udgX8HME0eu7NgWMs8wJ+QP3qLrzflMU1awzeIV1lXBdSHJ9+EweJx0lQy+pVKMWgX3abARVOB77jOftAJGjjQfugTI4lpdjK04XqFS2rAfmw4BkgmEVvZK3zratIBvT4he05bd7m9KP49Q8S3WjqBSAeik1dWhT01QU71rj/lKeWQr5Tt3G4ItVx4Z+K4Gd4uGXgeUcTqUfD6xuiqkNsMyLBMxc+taxdqN80TO9CwLyBorpn1mGaziYw/uxCrJuSOhu+SzddYfdDrsV2Kny4jZIiq0w==
    CIVO_API_URL: AgAwQxpPx2beTHmyk/byg4I5HZbS23GtLnhkLkSzmJeqrb/F8dShQqI/57RPOXNPkpnkWaJWVBeO6BPf1GUm1pFzDDpHuyuvgqCXexsW6trFoh00YxqtawspVD3STh2+glTB337byEgUznVERLk3FdaL+XedkgKnDhMeKL5OmM11MLuaWkd+4T9Ux7ns6szbXeSnw64fIclX4RKr4G8PtSgndGluHajPQ/0pNCCV/psPFHIJ7Q8P8J219sYhH7yZZbefQnjixn3yZgs0e4259x7yptyvlMTAM0pMVOHTMbE1L0xt5kjnT0YGo5xmI58gpC4CC72oH+YNQ1h1Mqt3CK5pcKiaBLPVb+CTgRir3gXkLx8cyFKMwpgjqqHnaBp5K8Dqx9FscFyEOM7hJv4wI1VAPXGnhQGvvbfW1IECDvHFK/D+sd0Z3CksT/OfGh7CH+fLak/rIRs4Jc0IaLm8fX28699LpeeXGI8il5nbwCBtCsMFqQOX0b/fLEoCtQC4bV/UkPYJIA+/DCgQqEGsUwDVDzXXWAvW3nMpp6eDbP91wnr5ivkdkAoD1KblcWtq8UzUs0UURJjY9D45831LnvwbHFan6kPeCoWzw/hVQsN0YkZqIgqnoAmVEfdTSk+13AUyopwgkwopWDH+fUwy4+oMUbLw15xNS21Y0TAEakDWLy3fTS4yvC1AbMhpJdO7HSyh0RAHMQ7tSiyZaB0tX4avUNb/6g==
    CIVO_CLUSTER_ID: AgCWLsHIEBUGLwSTEAqKX953Xq+MxCXz+gg5Qeke1v+Yo232C8HoksVdxdiWFGCh99C6BAO+miP1L4V5Roc4RKXzaMS2x1UDkhD2FTjMy2+kTN3SNAEYEFkjgB2ZAt/Br2m7UqxWBSbG/kXHAZ3yO01TTh1CRJGFv+gTZyYsY2JlL05yECB/+8QF1a4vfp3HxEJOdFVPf1mbZsp2ZNNaIu8XdspZYFW2yBcJp48PHyeeD1T/S1zMZBu+W9ywdXebk1zaGxc0mzdnVRI5QCzwxDfsugEgBp5okmh9XP1JnAk6t2GrTrxrZneigsOl6rl2aaPpovAdWUluewP0xYGndSYXqsn+KEijvyfrzwtRKVssyANzK28wCL445jEzMyrxb61Ozbetzu5ZBjN8LtZZhU1Wgbo82iMeJsGmqx7c5h3LBJSwoQ7222qXuLEtgAT+RNRzjM9OEwgkqOWpJuX0uQQTEVtQFyOFy6c0F+bR/6VvD823CnFpFW6bbDqnTqYrXOWs5YhUuHHwf+S4TV/g3FuPHen25C+JWPFIqTRNPv4W8MWZAeOjzKbkNl4GWM+3gY5PAMs0qaawHnw7/ltJgZN2y22taWqDRUtxDpPDJNUtyPQLpgvJ79hhJvmkuv9dn914rgpIxWyA3pa7i60dnJLgUQIjf7Inmqd+osLziulzhdx59Z+cMc4hy+QbxerkxYPM0xLzB/cyzOW/OlBxd6pE6mU3++P6d0sscbYGFRP9kJHOwJU=
    CIVO_REGION: AgAN2aJu0gt+iwjuFLsGSevGCS1S3eglwPpC84GQZP/aN49v8OO9czwxi5Uy8cK11851Uu+AKHecMm+Xfwtw+6rKGgZnAGG3pG3jNRZ3tzhxSHJbrImnghfrgtiQzarlTJJGPuCoGJi7lZOpnal7aouMnZ0miv+6VXZW8yBQaNl/EYk34gqgsfT4mZpqeqERSINGS/EenqKvzrcKkxhG70DEhGhBCJKlUY3cUkQgqo5zDVDqKbVxQ4as2vbZfk2j75i0+72P9blR3/ozpCN64bqwnhBmilwgMPPZSYuC/NSUBbI8MQu0lXawKTf+8apyGX7Q1HwVI3PU9QBRVi6kV1gwNFyIcMts5Rkv0SCbh8RKmexCw8CFhH5sZ5nPMi+S1SdtlOo5eE5NB5nvuUP6f7+Qwf8Vr0asWSR7cV6PVyx3Iyt8oYNleR3gJbaeMpN75nxiztZME9CQMzPU9O6CEfVVNjQc0YIz3Q5YhqEiRQBeJtQDUYlaZ6dY/WQVj+eiEcXQmESTm950TNvY7PztjbpH9RSevWbhc99xigHKv04llbrvAD/jA57wDWSD0l7g/x/JEWCpMFE7/0dfI1dcm90c+/5mmC+3ZLAkrezhzIwILnrPzJQn0yn5WMiMVKdrDrqNvPdsas6HNovWCLivmgFV+u1lXj8NjuWLAmtWiBOWe22vqbcpr63smSJUwv3oi9qIcB0r
  template:
    metadata:
      creationTimestamp: null
      name: cluster-autoscaler-civo
      namespace: kube-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.43.2"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: default
  values:
    cloudProvider: civo
    autoscalingGroups:
      - name: workers
        minSize: 2
        maxSize: 5
    extraArgs:
      skip-nodes-with-local-storage: "false"
      skip-nodes-with-system-pods: "false"
      scale-down-delay-after-add: "20m"
      scale-down-unneeded-time: "10m"
      scale-down-unready-time: "10m"
      scan-interval: "1m"
      max-node-provision-time: "10m"
      cordon-node-before-terminating: "true"
    envFromSecret: cluster-autoscaler-civo
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 150Mi
