apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.50.0"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: default
  values:
    cloudProvider: civo
    autoscalingGroups:
      - name: workers
        minSize: 2
        maxSize: 5
    extraArgs:
      skip-nodes-with-local-storage: "false"
      skip-nodes-with-system-pods: "false"
      scale-down-delay-after-add: "20m"
      scale-down-unneeded-time: "10m"
      scale-down-unready-time: "10m"
      scan-interval: "1m"
      max-node-provision-time: "10m"
      cordon-node-before-terminating: "true"
    envFromSecret: cluster-autoscaler-civo
    secretKeyRefNameOverride: cluster-autoscaler-civo
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 150Mi
