apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: kube-state-metrics
      version: "4.3.1"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: default
  values:
    installCRDs: true
---
