apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx
  namespace: default
spec:
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: default
  values:
    controller:
      replicaCount: 2
      watchIngressWithoutClass: true
      metrics:
        enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 90Mi
        limits:
          memory: 90Mi
      config:
        hsts: true
        hsts-include-subdomains: false
        custom-http-errors: "404,503"
    defaultBackend:
      enabled: true
      image:
        registry: registry.k8s.io
        image: ingress-nginx/custom-error-pages
        tag: v1.1.0
      extraVolumes:
      - name: custom-error-pages
        configMap:
          name: nginx-custom-error-pages
          items:
          - key: "404"
            path: "404.html"
          - key: "503"
            path: "503.html"
      extraVolumeMounts:
      - name: custom-error-pages
        mountPath: /www
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-error-pages
  namespace: kube-system
data:
  "404": |
    <!DOCTYPE html>
    <html>
      <head><title>PAGE NOT FOUND</title></head>
      <body>PAGE NOT FOUND</body>
    </html>
  "503": |
    <!DOCTYPE html>
    <html>
      <head><title>SERVICE UNAVAILABLE</title></head>
      <body>SERVICE UNAVAILABLE</body>
    </html>
