apiVersion: v1
kind: Namespace
metadata:
  name: url-to-grist
  labels:
    app.kubernetes.io/name: url-to-grist
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-to-grist
  namespace: url-to-grist
spec:
  encryptedData:
    GEMINI_TOKEN: AgBhS0lfsZL3Hmt04r0NLbxaXwyQpvoAL9h23inMdPE8ELW6GhUZc018BxrG6yil4AGuqbG1WD1682loIfwJJctXQsujF4C3FHpB/YS/GIZMnzBhcMkdAvD9iepnJv7Cu/obmE6R4rbgtR4a5L7TAURaDjkKTECc5zFz/5fwhcxvnIbCdvr/krdEJMNJdsyUP3uA140d9qgyddJemdH/m809wqwB2yeQjdxft4BslkuJe2BKL9I50fHFPPLt3J+FerhLXF++l4X2UBWAu7JkDRVNwbalEIffy9EKcIfYQhFr2sKahAWdzF+KBtx5ad5mGocUF/KKURvG8wIC7L4zdSEcgNDIlng1+WTZ3cLylh7piL85/qeWo9J0S3R2qrNO93yZnPEQaZTXk4i/Z3OknZmKyt5DehDVr432GyPp7H4xV69sYKcKyEfRwkkCbaDPRlLOoXl4ZSq7Ji960Wh1LrosJ8biQV4znH020PUbi8ozOPuKucVgbb+zznz0nmzGXK/VWQKofXoqY7u6r9fE9aKRrJdCDlYLQc9EWgw1GFlcp4Tc9m+uJ4qKK/H1qmA2F+qhHL5CpQF1A2OTw8+cIs5WRBEnrrzwO7Fzin6SYtljvq4ERZ7GSHf9Q0+Hrp/P5ep7Wb5dSkP8/Xd71cSUN528shDR5IzGzW3ySI9TFtiVt5isj9JKG7Ikato0LuUH+1TzvKgIMWPUC1jppsbd3z2Y62Y9kBEAjt7zLNSRM1P3LhNYBW9SLlU=
    GRIST_API_KEY: AgCJsqPMUhHbS7JsPuluZktygVTNeAuFrgtadAVec7ktg6o+aawm+j8+kKeKPkS8fFvXMLmfH9V9cQcM+xrf4j1/KspMy92Qbh9EjVVe7U4HQ9X8+OpI6dCp4hPl/nhNUZfcZrpLfX3Amhev9HXL7BoS7i9Jj56cxNYh5LSjRMql06qhAGAIvKVn21Z+D7biGMhw8vlEath3t9n3Z01W0+SJh3xXxkAqZoJXIFubkgUwfzypsp5/IsalIynV7/UVezpP1trmitZjGG5ivmLAP0on2XAMjHBwBcS5Qi7sBASvGlSZaBH4x4bF6WqJPB9a2/aeFXePu/n0QMgjh04PBpd0XO9VtZaem9i6ALM8a//Quy0GbMY0eux2Hz+RIkLDITb29sG1tXGbyUc7NXUiNhTPZ8dQxJyCRJ1ZsEsD1bKLp4c6CDmU0m9c1vtvsbb+gKHtDyHD6aXBiJ09eNKpJH26mhSL1j1gQDo8bbt8RHX/4pfXplI/HF4jLiHx4CqEN+zrZODi+Uz+qipKLJ+d8zP2RIS0N6AcaKpWLZ+g6lNBs5YeeNdOJMb2qp0o9nyY2TBaWhS44MFg6pwnd9N4Py8Ajt9FeZ/+U1N95LyCvHJI7oGKPHsbdLqCR2Gt30wY6zJdYLzx7rgjo0RU3ZZRJBdG5arvP+aSYEQPblWJ9Z9D/v/JbekOEiHbB2mXmPg5vgWOu1hJo6OD/goLH3Ary+sLlAzjnwJ57tqucmLVASe4O4UFDginFdz+
    GRIST_TABLE_URL: AgDE3y1FLEl5xdaCLScpuEk2gz2ByU1R40vlnbwNGsiDC9JhiQWkmRva3v6N5dxUnKpiDYldyANKo3GiiW1SgVM08k1icw2TFWKeaBHOj6Jpn3mDEFRorcyBies++n2SsNQXFOcI3HSqt1nRTLc3FnX30kSZWM4v0ob7CoOJQbzIlJMu8CVjkYTjwRI63nf3jI8+tuFKCri0opzqA+ketErJZoI+bic0hgBr1iAlGGnFwqmWIAGhjTgww/SL1/2bEsAmcMwcAYYfbHxHoHumaqFlBJohL+/xMa/3RQFDiqLtrpna9F0GFwGluYw2RjnwqcTDB5lK/2ZBtcgMXuHEBatHMdgLEDuz/PFe5D8/BtrwNIogAkZf1aJuUyJSBb/cDzFk6cVyylxOMu5JUL3BTMiz7Q8gaev37LqRkdHjfMy7xVpPCE7A/aoVfTBZeu5ZyvmRWC+2wZwAZyF1PvcSfh7ryfuk80HQ9SLEKLj9vcsoX1QCn2fe9JuGDx/E+J7e/P4pZPiLV4+enLbRUn6B9xj98mHUdpS+9RIwyEA9D3Ltls4FoGDix4GujGINIw5MlN7cXg59BVeZ4KA3/FwWNpNp2jk84/R4wxSk3N0lozHCnYktRNOJTcBG3WUr1wbqV//Kk+rTzRJTJw+b84oHtyRaLJi91b1gVAbmD8S2qJLzjZ4+H1LMjZyAO07yqhj0YyRsFO0EbWFB22uHvrLjMbWRQzso8Ubsoi5VAoXpJhlGss+UsJfKuErZwSM/AtiuRKvtZFVSlyXbMEmK3CkeAQg4ng1YF/RhpodyEBtIlHt5XkTzVHGwDifm46rjHmrx/8wO
    WEBSERVER_PASSWORD: AgBGYSrMITpMTfQV6x0gI3kOw87KlwKsj38ZaD+rMEYbvw1xxgT58G0lwePAtqJ8jszBiVoWYFPCDZA1cW28GxagdubG+asJcoMhghcj/WEi2fud/2qP8MxkC78ITK1UVt5BgVwYkvGLfte4zzcH0pu5Ipd4KDq+WS+s+CIDVX9Mqp+909JNaNBk4z709g2M6hBndcyHjzLCWUgxmXnZglLa19j4gOpA4/Q4ghB6wCnOZUU8aRy/DnjwLjM63wSJc6rMEqD7JEvDkxsgmu1BimM0vA2jYkTKorI0bWHtcXDTFkpUNYTRnpyf4HmZ1Dsjiy+KG1aPuTih/63xcu3tiPqm3MofrT9ERFFr4E/9lC186tzE93d+mw1zyFWR4PigoL+zbUiku9sUsz2sBxmRryNXU/zj7edXET0sBz0+5PFOu3WW6UTHSMg4x/BkUWHn4T7Spnem82Y6A65UJ58cqHqt1/oQTHueQp18N3Gf7ilq0X4/5sJy7aM/rCrwv9foJqK+rJI4sNrjpuyKoXXcseCvCk+ssqwqz7J3vE10TEWdSagfmI9mhfuxJz0khAHAWJtH364hlTPwmQbHdCGeZ8ekzdwtGOMT19xptCUzyryY2HVYTqOo63h2MU5jZe8O3UdCI//N0it3vx3/agJqgUc7JUTEbmY4YtwPKeUQsziovI97IMG+I8f8HzxwCCjqnenil0AWGmfns7hh2u1Dwy0MAwBkc0p2lg4tsajrz0M=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: url-to-grist
      name: url-to-grist
      namespace: url-to-grist
    type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: url-to-grist
  namespace: url-to-grist
  labels:
    app.kubernetes.io/name: url-to-grist
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: web
    name: web
  selector:
    app.kubernetes.io/name: url-to-grist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-to-grist
  namespace: url-to-grist
  labels:
    app.kubernetes.io/name: url-to-grist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: url-to-grist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: url-to-grist
    spec:
      containers:
      - name: web
        image: ghcr.io/namelessplanet/url-to-grist:v1.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: "url-to-grist"
        ports:
        - containerPort: 8080
          name: web
        livenessProbe:
          httpGet:
            port: web
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: web
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        resources:
          limits:
            memory: 20Mi
          requests:
            memory: 20Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-to-grist
  namespace: url-to-grist
  labels:
    app.kubernetes.io/name: url-to-grist
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - url-to-grist.cloudnative.now
    secretName: url-to-grist-ingress
  rules:
  - host: url-to-grist.cloudnative.now
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: url-to-grist
            port:
              number: 80
