apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vpa
  namespace: default
spec:
  url: https://charts.fairwinds.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vpa
  namespace: default
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: vpa
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: vpa
        namespace: default
  values:
    recommender:
      extraArgs:
        v: "4"
        pod-recommendation-min-cpu-millicores: 11
        pod-recommendation-min-memory-mb: 5
        on-by-default: true
    updater:
      enabled: false
    admissionController:
      enabled: false
---
