apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - extra-kustomizations.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/path
        value: ./cluster/flux-system
    target:
      kind: Kustomization
      name: flux-system
