name: "OpenTofu"

on:
  push:
    branches:
      - main
    paths:
      - 'infra/*'
      - '.github/workflows/opentofu.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/*'
      - '.github/workflows/opentofu.yaml'

concurrency:
  group: ${{ github.workflow }}

permissions:
  pull-requests: write
  contents: read

env:
  TF_VAR_github_token: "${{ secrets.GITHUB_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.TFSTATE_ACCESS_KEY }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.TFSTATE_SECRET_KEY }}"
  TF_VAR_civo_api_key: "${{ secrets.CIVO_TOKEN }}"
  CIVO_TOKEN: "${{ secrets.CIVO_TOKEN }}"

jobs:
  opentofu:
    name: 'OpenTofu'
    runs-on: ubuntu-latest

    if: "github.actor != 'Flux'"

    defaults:
      run:
        working-directory: infra

    steps:
    - uses: actions/checkout@v5
    - uses: opentofu/setup-opentofu@v1

    - name: OpenTofu fmt
      id: fmt
      run: tofu fmt -check
      continue-on-error: true

    - name: OpenTofu Init
      id: init
      run: tofu init -upgrade

    - name: OpenTofu Validate
      id: validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      id: plan
      run: tofu plan -no-color
      continue-on-error: true

    - name: Comment on PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('OpenTofu Format and Style')
          })

          // 2. Prepare format of the comment
          const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }

    - name: OpenTofu Apply
      if: github.event_name != 'pull_request'
      run: tofu apply -auto-approve -input=false
